### ISSUE TITLE
Call to undefined method DOMProcessingInstruction::getAttribute()

### ISSUE THREAD

**Issue by schweini** [enzojimenez/hacienda-firmador-php#2]
Hice un cli-wrapper al rededor del firmador (una vez que funcione, le hago un PR).
Pero no importa como lo intento, no loro firmar algo. Siempre me da el error siguiente.

```
PHP Fatal error:  Uncaught Error: Call to undefined method DOMProcessingInstruction::getAttribute() in /wwwroot/facturaDigital/hacienda-firmador-php/xmlseclibs/src/XMLSecurityDSig.php:284
Stack trace:
#0 /wwwroot/facturaDigital/hacienda-firmador-php/hacienda/firmador.php(73): RobRichards\XMLSecLibs\XMLSecurityDSig->setSignPolicy()
#1 /wwwroot/facturaDigital/hacienda-firmador-php/cli-wrapper.php(18): Hacienda\Firmador->firmarXml('fe_cert.p12', '2018', '<?xml version="...', 5, 'xml/2...')
#2 {main}
  thrown in /wwwroot/facturaDigital/hacienda-firmador-php/xmlseclibs/src/XMLSecurityDSig.php on line 284
```

**Comment by schweini** [comment]
en mis FEs, tengo la deinicion del XSLT (lo cual es valido y legal):

```<?xml version="1.0" encoding="utf-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="TiqueteElectronico.xsl"?>
<TiqueteElectronico ......
```

Si quito la parte del stylesheet, no me tira el error.

**Comment by schweini** [comment]
Y el error viene de la linea
`$xmlns = $this->xmlFirstChild->getAttribute('xmlns');
`
así que supongo que su código agarra el nodo del stylesheet, intenta de acceder el parámetro xmns, y se queja por que no hay.

**Comment by enzojimenez** [comment]
#4 
Gracias por el PR para mejor ese uso
